# Generated by Django 3.2.7 on 2021-10-29 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yelp_id", models.CharField(max_length=100)),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("Description", models.TextField()),
                ("Last_Modified", models.DateTimeField(auto_now_add=True)),
                ("Accessible", models.BooleanField(default=False)),
                ("FamilyFriendly", models.BooleanField(default=False)),
                ("TransactionRequired", models.BooleanField(default=True)),
            ],
        ),
    ]
