# Generated by Django 3.2.7 on 2021-10-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_of_restaurant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
