# Generated by Django 3.2.7 on 2021-10-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211011_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodredistributor',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodredistributor',
            name='name_of_food_redis',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
